# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\x12\x07storage\"]\n\x0ePrepareRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x11\n\tfile_size\x18\x03 \x01(\x03\x12\x14\n\x0ctotal_chunks\x18\x04 \x01(\x05\"1\n\x0fPrepareResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"W\n\x0c\x43hunkRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x10\n\x08\x63hunk_id\x18\x02 \x01(\x05\x12\x12\n\nchunk_data\x18\x03 \x01(\x0c\x12\x10\n\x08\x63hecksum\x18\x04 \x01(\t\">\n\rChunkResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0b\n\x03\x61\x63k\x18\x02 \x01(\x05\x12\x0f\n\x07node_id\x18\x03 \x01(\t\" \n\rStatusRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"z\n\x0eStatusResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x14\n\x0cstorage_used\x18\x03 \x01(\x03\x12\x18\n\x10storage_capacity\x18\x04 \x01(\x03\x12\x17\n\x0fstorage_percent\x18\x05 \x01(\x01\x32\xd8\x01\n\x13\x46ileTransferService\x12\x43\n\x0ePrepareReceive\x12\x17.storage.PrepareRequest\x1a\x18.storage.PrepareResponse\x12>\n\rTransferChunk\x12\x15.storage.ChunkRequest\x1a\x16.storage.ChunkResponse\x12<\n\tGetStatus\x12\x16.storage.StatusRequest\x1a\x17.storage.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREPAREREQUEST']._serialized_start=26
  _globals['_PREPAREREQUEST']._serialized_end=119
  _globals['_PREPARERESPONSE']._serialized_start=121
  _globals['_PREPARERESPONSE']._serialized_end=170
  _globals['_CHUNKREQUEST']._serialized_start=172
  _globals['_CHUNKREQUEST']._serialized_end=259
  _globals['_CHUNKRESPONSE']._serialized_start=261
  _globals['_CHUNKRESPONSE']._serialized_end=323
  _globals['_STATUSREQUEST']._serialized_start=325
  _globals['_STATUSREQUEST']._serialized_end=357
  _globals['_STATUSRESPONSE']._serialized_start=359
  _globals['_STATUSRESPONSE']._serialized_end=481
  _globals['_FILETRANSFERSERVICE']._serialized_start=484
  _globals['_FILETRANSFERSERVICE']._serialized_end=700
# @@protoc_insertion_point(module_scope)
