# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import storage_pb2 as storage__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in storage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileTransferServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrepareReceive = channel.unary_unary(
                '/storage.FileTransferService/PrepareReceive',
                request_serializer=storage__pb2.PrepareRequest.SerializeToString,
                response_deserializer=storage__pb2.PrepareResponse.FromString,
                _registered_method=True)
        self.TransferChunk = channel.unary_unary(
                '/storage.FileTransferService/TransferChunk',
                request_serializer=storage__pb2.ChunkRequest.SerializeToString,
                response_deserializer=storage__pb2.ChunkResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/storage.FileTransferService/GetStatus',
                request_serializer=storage__pb2.StatusRequest.SerializeToString,
                response_deserializer=storage__pb2.StatusResponse.FromString,
                _registered_method=True)


class FileTransferServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PrepareReceive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileTransferServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrepareReceive': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareReceive,
                    request_deserializer=storage__pb2.PrepareRequest.FromString,
                    response_serializer=storage__pb2.PrepareResponse.SerializeToString,
            ),
            'TransferChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferChunk,
                    request_deserializer=storage__pb2.ChunkRequest.FromString,
                    response_serializer=storage__pb2.ChunkResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=storage__pb2.StatusRequest.FromString,
                    response_serializer=storage__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'storage.FileTransferService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('storage.FileTransferService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileTransferService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PrepareReceive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.FileTransferService/PrepareReceive',
            storage__pb2.PrepareRequest.SerializeToString,
            storage__pb2.PrepareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.FileTransferService/TransferChunk',
            storage__pb2.ChunkRequest.SerializeToString,
            storage__pb2.ChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.FileTransferService/GetStatus',
            storage__pb2.StatusRequest.SerializeToString,
            storage__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
